"""
PPT Analysis Agent

This agent interprets the structured presentation data
generated by ppt_service.py.

Responsibilities:
    - Understand presentation structure
    - Identify common slide layouts
    - Classify slide types
    - Analyze typography
    - Analyze colors
    - Analyze visual elements
    - Analyze shape positioning
    - Build a reusable template profile

The template profile is later used by the PPT Generator
to create presentations that follow the uploaded template.
"""

from collections import Counter
from typing import Any
from app.services.llm_service import LLMService

class PPTAnalysisAgent:
    """
    Analyze an extracted PowerPoint presentation and
    produce a structured template profile.
    """

    def analyze(
        self,
        presentation: dict[str, Any]
    ) -> dict[str, Any]:
        """
        Analyze the complete PowerPoint structure.

        Parameters:
            presentation:
                Output returned by ppt_service.py.

        Returns:
            Structured template profile.
        """

        slides = presentation.get("slides", [])

        # -----------------------------------------------------------
        # Basic structure
        # -----------------------------------------------------------

        layouts = [
            slide.get("layout")
            for slide in slides
            if slide.get("layout")
        ]

        layout_frequency = Counter(layouts)

        # -----------------------------------------------------------
        # Typography analysis
        # -----------------------------------------------------------

        fonts = []

        for slide in slides:
            fonts.extend(
                slide.get("fonts", [])
            )

        font_names = [
            font.get("name")
            for font in fonts
            if font.get("name")
        ]

        font_sizes = [
            font.get("size")
            for font in fonts
            if font.get("size") is not None
        ]

        font_frequency = Counter(font_names)

        # -----------------------------------------------------------
        # Color analysis
        # -----------------------------------------------------------

        colors = self._collect_colors(slides)

        color_frequency = Counter(colors)

        # -----------------------------------------------------------
        # Slide classification
        # -----------------------------------------------------------

        slide_types = []

        for slide in slides:

            slide_type = self._classify_slide(slide)

            slide_types.append(
                {
                    "slide_number": slide.get("slide_number"),
                    "type": slide_type,
                }
            )

        slide_type_frequency = Counter(
            item["type"]
            for item in slide_types
        )

        # -----------------------------------------------------------
        # Shape analysis
        # -----------------------------------------------------------

        shape_statistics = self._analyze_shapes(slides)

        # -----------------------------------------------------------
        # Background analysis
        # -----------------------------------------------------------

        backgrounds = self._analyze_backgrounds(slides)

        # -----------------------------------------------------------
        # Position/layout analysis
        # -----------------------------------------------------------

        layout_patterns = self._analyze_positions(slides)

        # -----------------------------------------------------------
        # Build final template profile
        # -----------------------------------------------------------

        return {
            "presentation": {
                "filename": presentation.get("filename"),
                "file_type": presentation.get("file_type"),
                "slide_count": len(slides),
                "slide_width_inches": presentation.get(
                    "slide_width_inches"
                ),
                "slide_height_inches": presentation.get(
                    "slide_height_inches"
                ),
            },

            "structure": {
                "layouts": dict(layout_frequency),

                "slide_types": slide_types,

                "slide_type_frequency": dict(
                    slide_type_frequency
                ),
            },

            "typography": {
                "fonts": dict(font_frequency),

                "font_sizes": {
                    "minimum": min(font_sizes)
                    if font_sizes else None,

                    "maximum": max(font_sizes)
                    if font_sizes else None,

                    "average": (
                        round(
                            sum(font_sizes) / len(font_sizes),
                            2
                        )
                        if font_sizes
                        else None
                    ),
                },
            },

            "colors": {
                "frequency": dict(color_frequency),

                "dominant_colors": [
                    color
                    for color, _ in color_frequency.most_common(10)
                ],
            },

            "visual_elements": {
                "image_slides": sum(
                    slide.get("has_image", False)
                    for slide in slides
                ),

                "table_slides": sum(
                    slide.get("has_table", False)
                    for slide in slides
                ),

                "chart_slides": sum(
                    slide.get("has_chart", False)
                    for slide in slides
                ),

                "shape_statistics": shape_statistics,
            },

            "background": backgrounds,

            "layout_patterns": layout_patterns,

            "style_guidelines": (
                self._create_style_guidelines(
                    layout_frequency,
                    font_frequency,
                    color_frequency,
                    slide_type_frequency,
                )
            ),
        }

    # ===============================================================
    # Slide Classification
    # ===============================================================

    @staticmethod
    def _classify_slide(
        slide: dict[str, Any]
    ) -> str:
        """
        Classify a slide according to its content and
        visual elements.
        """

        title = slide.get("title", "").strip()

        text = slide.get("text", [])

        has_image = slide.get(
            "has_image",
            False
        )

        has_table = slide.get(
            "has_table",
            False
        )

        has_chart = slide.get(
            "has_chart",
            False
        )

        # Chart slides have a strong visual structure.
        if has_chart:
            return "chart"

        if has_table:
            return "table"

        if has_image and text:
            return "image_content"

        if has_image and not text:
            return "visual"

        if title and len(text) <= 2:
            return "title_content"

        if text:
            return "content"

        return "empty"

    # ===============================================================
    # Color Analysis
    # ===============================================================

    @staticmethod
    def _collect_colors(
        slides: list[dict[str, Any]]
    ) -> list[str]:
        """
        Collect RGB colors used by fonts, fills,
        lines, and slide backgrounds.
        """

        colors = []

        for slide in slides:

            # -------------------------------------------------------
            # Background color
            # -------------------------------------------------------

            background = slide.get(
                "background"
            )

            if background:

                color = background.get(
                    "color"
                )

                if color:
                    rgb = color.get("rgb")

                    if rgb:
                        colors.append(rgb)

            # -------------------------------------------------------
            # Shape colors
            # -------------------------------------------------------

            for shape in slide.get(
                "shapes",
                []
            ):

                # Fill color
                fill = shape.get("fill")

                if fill:

                    fill_color = fill.get(
                        "color"
                    )

                    if fill_color:

                        rgb = fill_color.get(
                            "rgb"
                        )

                        if rgb:
                            colors.append(rgb)

                # Line color
                line = shape.get("line")

                if line:

                    line_color = line.get(
                        "color"
                    )

                    if line_color:

                        rgb = line_color.get(
                            "rgb"
                        )

                        if rgb:
                            colors.append(rgb)

                # Font colors
                for font in shape.get(
                    "fonts",
                    []
                ):

                    font_color = font.get(
                        "color"
                    )

                    if font_color:

                        rgb = font_color.get(
                            "rgb"
                        )

                        if rgb:
                            colors.append(rgb)

        return colors

    # ===============================================================
    # Shape Analysis
    # ===============================================================

    @staticmethod
    def _analyze_shapes(
        slides: list[dict[str, Any]]
    ) -> dict[str, Any]:
        """
        Count the different types of shapes used
        throughout the presentation.
        """

        shape_types = []

        for slide in slides:

            for shape in slide.get(
                "shapes",
                []
            ):

                shape_type = shape.get(
                    "shape_type"
                )

                if shape_type:
                    shape_types.append(
                        shape_type
                    )

        frequency = Counter(
            shape_types
        )

        return {
            "total_shapes": len(shape_types),

            "types": dict(frequency),
        }

    # ===============================================================
    # Background Analysis
    # ===============================================================

    @staticmethod
    def _analyze_backgrounds(
        slides: list[dict[str, Any]]
    ) -> dict[str, Any]:
        """
        Analyze slide background patterns.
        """

        background_types = []

        background_colors = []

        for slide in slides:

            background = slide.get(
                "background"
            )

            if not background:
                continue

            background_type = background.get(
                "type"
            )

            if background_type:
                background_types.append(
                    background_type
                )

            color = background.get(
                "color"
            )

            if color:

                rgb = color.get(
                    "rgb"
                )

                if rgb:
                    background_colors.append(
                        rgb
                    )

        return {
            "types": dict(
                Counter(background_types)
            ),

            "colors": dict(
                Counter(background_colors)
            ),
        }

    # ===============================================================
    # Position Analysis
    # ===============================================================

    @staticmethod
    def _analyze_positions(
        slides: list[dict[str, Any]]
    ) -> dict[str, Any]:
        """
        Analyze where shapes are generally positioned.

        This gives the generator a basic understanding of
        the template's visual hierarchy.
        """

        positions = []

        for slide in slides:

            for shape in slide.get(
                "shapes",
                []
            ):

                position = shape.get(
                    "position"
                )

                if not position:
                    continue

                positions.append(
                    position
                )

        if not positions:
            return {
                "shape_count": 0,
                "average_position": None,
            }

        left_values = [
            p["left"]
            for p in positions
            if p.get("left") is not None
        ]

        top_values = [
            p["top"]
            for p in positions
            if p.get("top") is not None
        ]

        width_values = [
            p["width"]
            for p in positions
            if p.get("width") is not None
        ]

        height_values = [
            p["height"]
            for p in positions
            if p.get("height") is not None
        ]

        return {
            "shape_count": len(positions),

            "average_position": {
                "left": (
                    round(
                        sum(left_values)
                        / len(left_values),
                        2
                    )
                    if left_values
                    else None
                ),

                "top": (
                    round(
                        sum(top_values)
                        / len(top_values),
                        2
                    )
                    if top_values
                    else None
                ),

                "width": (
                    round(
                        sum(width_values)
                        / len(width_values),
                        2
                    )
                    if width_values
                    else None
                ),

                "height": (
                    round(
                        sum(height_values)
                        / len(height_values),
                        2
                    )
                    if height_values
                    else None
                ),
            },
        }

    # ===============================================================
    # Style Guidelines
    # ===============================================================

    @staticmethod
    def _create_style_guidelines(
        layout_frequency: Counter,
        font_frequency: Counter,
        color_frequency: Counter,
        slide_type_frequency: Counter,
    ) -> dict[str, Any]:
        """
        Convert raw statistics into practical
        template-generation guidelines.
        """

        most_common_layout = (
            layout_frequency.most_common(1)[0][0]
            if layout_frequency
            else None
        )

        most_common_font = (
            font_frequency.most_common(1)[0][0]
            if font_frequency
            else None
        )

        dominant_color = (
            color_frequency.most_common(1)[0][0]
            if color_frequency
            else None
        )

        common_slide_type = (
            slide_type_frequency.most_common(1)[0][0]
            if slide_type_frequency
            else None
        )

        return {
            "preferred_layout": most_common_layout,

            "preferred_font": most_common_font,

            "dominant_color": dominant_color,

            "common_slide_type": common_slide_type,

            # These are explicit constraints for the
            # future PPT generator.
            "preserve_existing_layouts": True,

            "preserve_existing_typography": True,

            "preserve_visual_hierarchy": True,

            "preserve_template_colors": True,

            "preserve_shape_positions": True,
        }